name: iText
options:
  bundleIdPrefix: com.jonathan
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
targets:
  iText-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jonathan.iText
        INFOPLIST_FILE: Configuration/Info-macOS.plist
        CODE_SIGN_ENTITLEMENTS: Configuration/iText-macOS.entitlements
        PRODUCT_NAME: iText
  iText-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jonathan.iText
        INFOPLIST_FILE: Configuration/Info-iOS.plist
        CODE_SIGN_ENTITLEMENTS: Configuration/iText-iOS.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        PRODUCT_NAME: iText
