name: iMD
options:
  bundleIdPrefix: com.jonathan
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
targets:
  iMD:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jonathan.iMD
        INFOPLIST_FILE: Configuration/Info-macOS.plist
        CODE_SIGN_ENTITLEMENTS: Configuration/iMD-macOS.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: iMD
